1. Import pandas and load the data


# Import pandas
import pandas as pd

In [5]:
import pandas as pd

In [7]:
  

# Check the versions used to train the model
import sys
import sklearn
import pandas
import joblib

print("Python version      :", sys.version)
print("Scikit-learn version:", sklearn.__version__)
print("Pandas version      :", pandas.__version__)
print("Joblib version      :", joblib.__version__)

Python version      : 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
Scikit-learn version: 1.9.0
Pandas version      : 3.0.5
Joblib version      : 1.5.3

In [8]:
# File location
file_path = "../raw/heart_disease.csv"

# Read the heart disease dataset
heart_df = pd.read_csv(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

2. Show the first five rows

In [9]:

# Display the first 5 rows
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num,target_binary
0,63.0,1,1,145.0,233.0,1,2,150.0,0,2.3,3,0.0,6.0,0,0
1,67.0,1,4,160.0,286.0,0,2,108.0,1,1.5,2,3.0,3.0,2,1
2,67.0,1,4,120.0,229.0,0,2,129.0,1,2.6,2,2.0,7.0,1,1
3,37.0,1,3,130.0,250.0,0,0,187.0,0,3.5,3,0.0,3.0,0,0
4,41.0,0,2,130.0,204.0,0,2,172.0,0,1.4,1,0.0,3.0,0,0

In [10]:

# Number of rows and columns
heart_df.shape

(1024, 15)

In [11]:


# Display column names
heart_df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num', 'target_binary'],
      dtype='str')

3. Check dataset information

In [12]:

# Data types and missing values
heart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            1024 non-null   float64
 1   sex            1024 non-null   int64
 2   cp             1024 non-null   int64
 3   trestbps       1024 non-null   float64
 4   chol           1024 non-null   float64
 5   fbs            1024 non-null   int64
 6   restecg        1024 non-null   int64
 7   thalach        1024 non-null   float64
 8   exang          1024 non-null   int64
 9   oldpeak        1024 non-null   float64
 10  slope          1024 non-null   int64
 11  ca             1024 non-null   float64
 12  thal           1024 non-null   float64
 13  num            1024 non-null   int64
 14  target_binary  1024 non-null   int64
dtypes: float64(7), int64(8)
memory usage: 120.1 KB

4. Show statistical summary

In [13]:

# Summary of numerical columns
heart_df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num,target_binary
count,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000,1024.000000
mean,54.532202,0.685547,3.149414,131.478621,246.965108,0.165039,1.001953,149.638107,0.345703,1.090142,1.619141,0.681641,4.701172,0.923828,0.458984
std,9.273400,0.464525,0.971812,17.506230,52.561237,0.371397,0.993624,23.480260,0.475829,1.072306,0.620176,0.947402,1.941107,1.070377,0.498558
min,18.000000,0.000000,1.000000,84.869643,100.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,48.193472,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.555581,0.000000,0.152062,1.000000,0.000000,3.000000,0.000000,0.000000
50%,55.000000,1.000000,3.000000,130.012111,244.996816,0.000000,1.000000,151.524700,0.000000,0.854977,2.000000,0.000000,3.000000,0.000000,0.000000
75%,61.196437,1.000000,4.000000,142.412148,280.232245,0.000000,2.000000,165.642437,1.000000,1.630471,2.000000,1.000000,7.000000,2.000000,1.000000
max,78.795030,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,227.196592,1.000000,6.200000,3.000000,3.000000,7.000000,4.000000,1.000000