1. Import pandas and load the data


# Import pandas
import pandas as pd

In [22]:
import pandas as pd

heart_df = pd.read_csv("../data/raw/heart_disease.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

2. Show the first five rows

In [9]:

# Display the first 5 rows
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num,target_binary
0,63.0,1,1,145.0,233.0,1,2,150.0,0,2.3,3,0.0,6.0,0,0
1,67.0,1,4,160.0,286.0,0,2,108.0,1,1.5,2,3.0,3.0,2,1
2,67.0,1,4,120.0,229.0,0,2,129.0,1,2.6,2,2.0,7.0,1,1
3,37.0,1,3,130.0,250.0,0,0,187.0,0,3.5,3,0.0,3.0,0,0
4,41.0,0,2,130.0,204.0,0,2,172.0,0,1.4,1,0.0,3.0,0,0

In [10]:

# Number of rows and columns
heart_df.shape

(1024, 15)

In [11]:


# Display column names
heart_df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num', 'target_binary'],
      dtype='str')

3. Check dataset information

In [12]:

# Data types and missing values
heart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            1024 non-null   float64
 1   sex            1024 non-null   int64
 2   cp             1024 non-null   int64
 3   trestbps       1024 non-null   float64
 4   chol           1024 non-null   float64
 5   fbs            1024 non-null   int64
 6   restecg        1024 non-null   int64
 7   thalach        1024 non-null   float64
 8   exang          1024 non-null   int64
 9   oldpeak        1024 non-null   float64
 10  slope          1024 non-null   int64
 11  ca             1024 non-null   float64
 12  thal           1024 non-null   float64
 13  num            1024 non-null   int64
 14  target_binary  1024 non-null   int64
dtypes: float64(7), int64(8)
memory usage: 120.1 KB

In [13]:
heart_df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num,target_binary
1019,60.072205,1,3,115.422056,181.768595,0,0,128.155858,1,1.001941,2,1.0,7.0,2,1
1020,70.928404,1,2,166.727221,244.993631,1,0,108.481311,0,0.698337,2,1.0,7.0,2,1
1021,57.332875,1,2,105.075177,233.146324,0,2,140.342007,0,1.519138,1,0.0,7.0,2,1
1022,40.881554,0,4,125.068578,154.370678,1,2,123.756294,0,1.936684,2,1.0,7.0,2,1
1023,46.863367,1,3,121.909777,291.175476,1,2,146.652276,1,1.913951,2,2.0,3.0,2,1

 Check missing values

In [14]:
# Count missing values in every column
heart_df.isnull().sum()

age              0
sex              0
cp               0
trestbps         0
chol             0
fbs              0
restecg          0
thalach          0
exang            0
oldpeak          0
slope            0
ca               0
thal             0
num              0
target_binary    0
dtype: int64

Check duplicate rows

In [16]:

# Count duplicated rows
heart_df.duplicated().sum()

np.int64(0)

In [18]:
heart_df.dtypes

age              float64
sex                int64
cp                 int64
trestbps         float64
chol             float64
fbs                int64
restecg            int64
thalach          float64
exang              int64
oldpeak          float64
slope              int64
ca               float64
thal             float64
num                int64
target_binary      int64
dtype: object

save the data

In [23]:
# Save the cleaned dataset
heart_df.to_csv("../data/cleaned/heart_disease_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!